# This is a basic workflow to help you get started with Actions

name: Newman CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  newman:
    name: Postman-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Install Newman & Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      # Make directory for test results in workspace
      - name: Make Directory
        run: mkdir -p newman-results
        
      # Run newman cli
      - name: Run Newman
        run: |
          newman run "Postman Collections/API_Newman_PassedTests.json" -r htmlextra
     
      # Upload test results to workspace
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: Postman_Test_Report
          path: newman-results
